main: cn.wode490390.nukkit.atlantisgen.AtlantisGeneratorPlugin
name: "AtlantisGenerator"
author: "wode490390"
description: "Atlantis generator plugin for Nukkit"
website: "http://wode490390.cn/"
version: "${pom.version}"
api: ["1.0.11"]
load: STARTUP
